name: Build, test and lint
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        shell: bash
      - name: Build project
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        shell: bash
      - name: Run linter
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        shell: bash
      - name: Run test
        run: pnpm run test
